#!/bin/bash

#./make_video_corruption_interpolation.sh /shed/data/mlp_image_reconstruction_output/mabel_ithaca_experiment_256x5_corruption_experiment/interpolation_to_zero/layer_01_sigma_1p0e-02/ /shed/data/mlp_image_reconstruction_output/mabel_ithaca_experiment_256x5_corruption_experiment/videos/interp_to_zero_layer_01_sigma_1p0e-02.mkv
./make_video_corruption_interpolation.sh /shed/data/mlp_image_reconstruction_output/mabel_ithaca_experiment_256x5_corruption_experiment/interpolation_to_zero/layer_02_sigma_1p0e-02/ /shed/data/mlp_image_reconstruction_output/mabel_ithaca_experiment_256x5_corruption_experiment/videos/interp_to_zero_layer_02_sigma_1p0e-02.mkv
